# k3s/deploy.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    app: html-app
    version: "1.0"
spec:
  replicas: 1  # K3s এর জন্য optimized
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # Zero downtime deployment
      maxSurge: 1
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-app
        image: ghcr.io/saroarshahan/k3s-hub:latest  # Will be replaced by workflow
        ports:
        - containerPort: 80
          name: http
        imagePullPolicy: Always
        resources:
          requests:
            memory: "32Mi"    # K3s lightweight resources
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      imagePullSecrets:
      - name: ghcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: html-app-service
  labels:
    app: html-app
spec:
  selector:
    app: html-app
  type: NodePort  # K3s এর জন্য perfect
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30100
    name: http