# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  K3S_SERVER: ${{ secrets.K3S_SERVER }}
  USER_NAME: saroarshahan

jobs:
  # Build and push (calls separate workflow)
  build:
    uses: ./.github/workflows/build-and-push.yaml
    secrets: inherit

   # Deploy to staging (automatic on main branch)
  deploy:
    needs: build
    if: |
      always() && 
      needs.build.result == 'success' && 
      (github.ref == 'refs/heads/main') &&
      github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: main
      image_tag: latest
    secrets: inherit
  
  # Manual deployment (workflow_dispatch)
  deploy-manual:
    needs: build
    if: |
      always() && 
      needs.build.result == 'success' && 
      (github.ref == 'refs/heads/main') &&
      github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: main
      image_tag: latest
    secrets: inherit
  
