name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Push the Docker Image
        run: |
          echo "Docker Login to GHCR..."
          docker login --username ${{ github.repository_owner }} -p ${{ secrets.GHCR_TOKEN }} ghcr.io

          echo "Building Docker image..."
          docker build -t ghcr.io/${{ github.repository_owner.toLowerCase() }}/k3s-hub:latest .

          echo "Pushing Docker image to GHCR..."
          docker push ghcr.io/${{ github.repository_owner.toLowerCase() }}/k3s-hub:latest
          echo "Docker image published successfully!"